require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ActualTempReadingsController do

  # This should return the minimal set of attributes required to create a valid
  # ActualTempReading. As you add validations to ActualTempReading, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "value" => "1.5" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ActualTempReadingsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all actual_temp_readings as @actual_temp_readings" do
      actual_temp_reading = ActualTempReading.create! valid_attributes
      get :index, {}, valid_session
      assigns(:actual_temp_readings).should eq([actual_temp_reading])
    end
  end

  describe "GET show" do
    it "assigns the requested actual_temp_reading as @actual_temp_reading" do
      actual_temp_reading = ActualTempReading.create! valid_attributes
      get :show, {:id => actual_temp_reading.to_param}, valid_session
      assigns(:actual_temp_reading).should eq(actual_temp_reading)
    end
  end

  describe "GET new" do
    it "assigns a new actual_temp_reading as @actual_temp_reading" do
      get :new, {}, valid_session
      assigns(:actual_temp_reading).should be_a_new(ActualTempReading)
    end
  end

  describe "GET edit" do
    it "assigns the requested actual_temp_reading as @actual_temp_reading" do
      actual_temp_reading = ActualTempReading.create! valid_attributes
      get :edit, {:id => actual_temp_reading.to_param}, valid_session
      assigns(:actual_temp_reading).should eq(actual_temp_reading)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ActualTempReading" do
        expect {
          post :create, {:actual_temp_reading => valid_attributes}, valid_session
        }.to change(ActualTempReading, :count).by(1)
      end

      it "assigns a newly created actual_temp_reading as @actual_temp_reading" do
        post :create, {:actual_temp_reading => valid_attributes}, valid_session
        assigns(:actual_temp_reading).should be_a(ActualTempReading)
        assigns(:actual_temp_reading).should be_persisted
      end

      it "redirects to the created actual_temp_reading" do
        post :create, {:actual_temp_reading => valid_attributes}, valid_session
        response.should redirect_to(ActualTempReading.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved actual_temp_reading as @actual_temp_reading" do
        # Trigger the behavior that occurs when invalid params are submitted
        ActualTempReading.any_instance.stub(:save).and_return(false)
        post :create, {:actual_temp_reading => { "value" => "invalid value" }}, valid_session
        assigns(:actual_temp_reading).should be_a_new(ActualTempReading)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ActualTempReading.any_instance.stub(:save).and_return(false)
        post :create, {:actual_temp_reading => { "value" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested actual_temp_reading" do
        actual_temp_reading = ActualTempReading.create! valid_attributes
        # Assuming there are no other actual_temp_readings in the database, this
        # specifies that the ActualTempReading created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ActualTempReading.any_instance.should_receive(:update_attributes).with({ "value" => "1.5" })
        put :update, {:id => actual_temp_reading.to_param, :actual_temp_reading => { "value" => "1.5" }}, valid_session
      end

      it "assigns the requested actual_temp_reading as @actual_temp_reading" do
        actual_temp_reading = ActualTempReading.create! valid_attributes
        put :update, {:id => actual_temp_reading.to_param, :actual_temp_reading => valid_attributes}, valid_session
        assigns(:actual_temp_reading).should eq(actual_temp_reading)
      end

      it "redirects to the actual_temp_reading" do
        actual_temp_reading = ActualTempReading.create! valid_attributes
        put :update, {:id => actual_temp_reading.to_param, :actual_temp_reading => valid_attributes}, valid_session
        response.should redirect_to(actual_temp_reading)
      end
    end

    describe "with invalid params" do
      it "assigns the actual_temp_reading as @actual_temp_reading" do
        actual_temp_reading = ActualTempReading.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ActualTempReading.any_instance.stub(:save).and_return(false)
        put :update, {:id => actual_temp_reading.to_param, :actual_temp_reading => { "value" => "invalid value" }}, valid_session
        assigns(:actual_temp_reading).should eq(actual_temp_reading)
      end

      it "re-renders the 'edit' template" do
        actual_temp_reading = ActualTempReading.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ActualTempReading.any_instance.stub(:save).and_return(false)
        put :update, {:id => actual_temp_reading.to_param, :actual_temp_reading => { "value" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested actual_temp_reading" do
      actual_temp_reading = ActualTempReading.create! valid_attributes
      expect {
        delete :destroy, {:id => actual_temp_reading.to_param}, valid_session
      }.to change(ActualTempReading, :count).by(-1)
    end

    it "redirects to the actual_temp_readings list" do
      actual_temp_reading = ActualTempReading.create! valid_attributes
      delete :destroy, {:id => actual_temp_reading.to_param}, valid_session
      response.should redirect_to(actual_temp_readings_url)
    end
  end

end
